---
app:
#  botUrl:
container:
#  resources:
deployment:
  replicas: 1
factomd:
  host: localhost
  port: 8088
image:
  repository: hub.docker.com/bedrocksolutions/tfa-bot
pod:
  restartPolicy: Always
...