---
app: {}
#  botUrl:
container:
  resources:
    requests:
      memory: 96Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 100m
deployment:
  replicas: 1
factomd:
  host: localhost
  port: 8088
image:
  name: tfa-bot
  namespace: bedrocksolutions
  pullPolicy: Always
  tag: latest
pod:
  restartPolicy: Always
...