---
apiVersion: v1
kind: StatefulSet
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  containers:
    - name: {{ .Chart.Name }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      resources:
{{ .Values.container.resources | toYaml | indent 8 }}
      volumeMounts:
        - name: {{ template "app.fullname" . }}-config-volume
          mountPath: {{ .Values.volumes.config.mountPath }}
        - name: {{ template "app.fullname" . }}-db-volume
          mountPath: {{ .Values.volumes.db.mountPath }}
  replicas: {{ .Values.statefulSet.replicas }}
  restartPolicy: {{ .Values.pod.restartPolicy }}
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        release: {{ .Release.Name }}
  volumes:
    - name: {{ template "app.fullname" . }}-config-volume
      configMap:
        name: {{ template "app.fullname" . }}
        items:
        - key: config.json
    - name: {{ template "app.fullname" . }}-db-volume
      dbVolumeClaim:
        claimName: {{ template "app.fullname" . }}
...