---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "app.fullname" . }}-statefulset
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.statefulSet.replicas }}
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        chart: {{ template "app.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: failure-domain.beta.kubernetes.io/zone
                operator: In
                values:
                - us-west1-a
                - us-west1-b
      containers:
        - name: {{ template "app.fullname" . }}-container
          command:
            - tail
            - -f
            - /dev/null
          image: "{{ .Values.image.namespace }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          resources:
{{ .Values.container.resources | toYaml | indent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: {{ .Values.volumes.config.mountPath }}
            - name: csv-volume
              mountPath: {{ .Values.volumes.csv.mountPath }}
            - name: db-volume
              mountPath: {{ .Values.volumes.db.mountPath }}
      restartPolicy: {{ .Values.pod.restartPolicy }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "app.fullname" . }}-configmap
  volumeClaimTemplates:
    - metadata:
        name: csv-volume
        labels:
          app: {{ template "app.name" . }}
          chart: {{ template "app.chart" . }}
          release: {{ .Release.Name }}
          heritage: {{ .Release.Service }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistentVolumeClaim.initialSize }}
        storageClassName: {{ template "app.fullname" . }}-storageclass
    - metadata:
        name: db-volume
        labels:
          app: {{ template "app.name" . }}
          chart: {{ template "app.chart" . }}
          release: {{ .Release.Name }}
          heritage: {{ .Release.Service }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistentVolumeClaim.initialSize }}
        storageClassName: {{ template "app.fullname" . }}-storageclass
...
