---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.statefulSet.replicas }}
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.namespace }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          resources:
{{ .Values.container.resources | toYaml | indent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: {{ .Values.volumes.config.mountPath }}
            - name: db-volume
              mountPath: {{ .Values.volumes.db.mountPath }}
      restartPolicy: {{ .Values.pod.restartPolicy }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "app.fullname" . }}
            items:
            - key: config.json
  volumeClaimTemplates:
    - metadata:
        name: db-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistentVolumeClaim.initialSize }}
        storageClassName: {{ template "app.fullname" . }}
...
