---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ template "app.fullname" . }}
provisioner: {{ .Values.storageClass.provisioner }}
parameters:
{{ .Values.storageClass.parameters | toYaml | indent 2 }}
allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values:
{{ .Values.storageClass.zones | toYaml | indent 6 }}
allowVolumeExpansion: true
volumeBindingMode: Immediate
reclaimPolicy: Retain
...