---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ template "app.fullname" . }}
provisioner: {{ .Values.storageClass.provisioner }}
parameters:
{{ .Values.storageClass.parameters | toYaml | indent 2 }}
allowVolumeExpansion: true
volumeBindingMode: Immediate
reclaimPolicy: Retain
...