---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}"
    spec:
      containers:
        - name: {{ .Release.Name }}
        {{- with .Values}}
          image: {{ .image }}:{{ .imagetag }}
          ports:
          - containerPort: 8089
            name: factom-walletd
            protocol: TCP
          livenessProbe:
            tcpSocket:
              port: factom-walletd
              initialDelaySeconds: 120
              periodSeconds: 30
              timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: factom-walletd
              initialDelaySeconds: 100
              periodSeconds: 30
              timeoutSeconds: 5
          resources:
            {{- with .resources}}
            limits:
              cpu: {{.cpu}}
              memory: {{.memory}}
            requests:
              cpu: {{.cpu}}
              memory: {{.memory}}
            {{- end}}
        {{- end}}
