---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.fullname" . }}-cfg
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ $f := .Values.factomd -}}
{{- include "factomd.argValue" (dict "factomd" $f "key" "configFilePath") | base | quote | indent 2 -}}: |-
    [app]
{{ $mergedNames := merge (index $f._config.names $f.network) $f._config.names.global -}}
{{- $mergedValues := merge $f.config (index $f._config.defaults $f.network) $f._config.defaults.global -}}
{{- range $key, $configName := $mergedNames -}}
{{- $value := (index $mergedValues $key) | default "" -}}
{{- printf "; 'factomd.config.%s' --> %s" $key $configName | indent 4 }}
{{ $comment := "" -}}
{{- if not $value -}}
{{- $comment = "; " -}}
{{- else if eq $f.role "follower" -}}
{{- if eq $key "identityChainID" -}}
{{- $value = include "factomd.configDefault" (dict "factomd" $f "key" "identityChainID") -}}
{{- else if or (eq $key "localServerPrivateKey") (eq $key "localServerPublicKey") -}}
{{- $comment = "; " -}}
{{- end -}}
{{- end -}}
{{- printf "%s%s=%s\n" $comment $configName (toString $value) | indent 4 }}
{{ end -}}
...
