---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.fullname" . }}-factomd-config
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  factomd.conf: |-
[app]
{{- with .Values.factomd -}}
{{- $factomd := . -}}
{{- $overrides := .overrides.config -}}
{{- $global := .config.defaults.global -}}
{{- $network := index .config.defaults .network -}}
{{- range $key, $value := (merge $overrides $network $global) }}
{{- if $value }}
{{ include "factomd.configKey" (dict "factomd" $factomd "key" $key) }}={{ $value -}}
{{ end -}}
{{- end -}}
{{- end }}
...