---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.fullname" . }}-factomd-config
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  factomd.conf: |-
[app]
{{- with .Values.factomd -}}
{{- $merged := merge .overrides .defaults.global (index .defaults .network) -}}
{{- $factomd := . -}}
{{- range $key, $value := $merged }}
{{- if $value -}}
{{ include "factomd.configKey" (dict "factomd" $factomd "key" $key) }}={{ $value }}
{{ end -}}
{{- end -}}
{{- end }}
...