---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.fullname" . }}-factomd-config
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  factomd.conf: |-
    [app]
    ControlPanelSetting            = readonly
    ControlPanelPort               = 8090
    LocalNetworkPort               = 8110
    {{ if .Values.factomd.testnet }}
    CustomNetworkPort              = 8110
    CustomSpecialPeers             = ""
    CustomBootstrapIdentity        = 8888882f5002ff95fce15d20ecb7e18ae6cc4d5849b372985d856b56e492ae0f
    CustomBootstrapKey             = 58cfccaa48a101742845df3cecde6a9f38037030842d34d0eaa76867904705ae
    CustomSeedURL                  = "https://raw.githubusercontent.com/FactomProject/communitytestnet/master/seeds/testnetseeds.txt"
    DirectoryBlockInSeconds        = 600
    ExchangeRateAuthorityPublicKey = 58cfccaa48a101742845df3cecde6a9f38037030842d34d0eaa76867904705ae
    network                        = CUSTOM
    {{ else }}
    MainSpecialPeers               = "52.17.183.121:8108 52.17.153.126:8108 52.19.117.149:8108 52.18.72.212:8108"
    {{ end }}
    IdentityChainID						 	   = {{ .Values.factomd.authority.chainID | default "FA1E000000000000000000000000000000000000000000000000000000000000" }}
    ;ChangeAcksHeight              = 0