---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "app.fullname" . }}
spec:
  ports:
  - name: api
    port: 8088
    targetPort: api
  - name: control-panel
    port: 8090
    targetPort: control-panel
  - name: testnet
    port: 8110
    targetPort: testnet
  selector:
    app: {{ template "app.name" . }}
  type: NodePort
