---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "app.fullname" . }}-ss
spec:
  replicas: {{ .Values.statefulSet.replicas }}
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
    spec:
      containers:
      - name: {{ template "app.name" . }}
        args:
        - "-config=/home/factomd/.factom/private/factomd.conf"
{{- $f := .Values.factomd }}
{{- $merged := merge $f.args $f._args.defaults.global (index $f._args.defaults $f.network) }}
{{- range $key, $value := $merged }}
{{- if $value }}
{{- $argName := include "factomd.argKey" (dict "factomd" $f "key" $key) }}
{{ printf "- \"-%s=%s\"" $argName (toString $value) | indent 8 }}
{{- end }}
{{- end }}
        image: {{ .Values.container.image }}:{{ .Values.container.imageTag }}
        livenessProbe:
          tcpSocket:
            port: {{ include "factomd.configValue" (dict "factomd" .Values.factomd "key" "p2pPort") }}
          initialDelaySeconds: 120
          periodSeconds: 10
        ports:
{{- range $service := .Values.services }}
        - containerPort: {{ include "factomd.configValue" (dict "factomd" $.Values.factomd "key" $service.configPortName) }}
          name: {{ $service.name }}
          protocol: TCP
{{- end }}
        readinessProbe:
          tcpSocket:
            port: {{ include "factomd.configValue" (dict "factomd" .Values.factomd "key" "p2pPort") }}
          initialDelaySeconds: 120
          periodSeconds: 10
        resources:
{{ toYaml .Values.container.resources | indent 10 }}
        volumeMounts:
        - name: factomd-database
          mountPath: /home/factomd/.factom/m2
        - name: factomd-config
          mountPath: /home/factomd/.factom/private
      volumes:
      - name: factomd-config
        configMap:
          name: {{ template "app.fullname" . }}-cfg
  volumeClaimTemplates:
  - metadata:
      name: factomd-database
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.persistentVolumeClaim.size }}
      storageClassName: {{ template "app.fullname" . }}-sc
...