---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ template "app.fullname" . }}-sc
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if eq .Values.cloudProvider "gcp" }}
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
{{- end }}
allowVolumeExpansion: true
volumeBindingMode: Immediate
reclaimPolicy: Retain
...