---
apiVersion: v1
name: factomd
home: https://github.com/FactomProject/factomd
version: 0.0.1
description: factomd helm chart
sources:
  - https://github.com/BedrockSolutions/helm/factomd
maintainers:
  - name: Bedrock Solutions
    email: info@bedrocksolutions.io
