---
factomd:
  image: factominc/factomd
  imageTag: v6.0.1-alpine
  databaseDisk:
    size: 20Gi
  replicaCount: 1
  resources:
    cpu: 1000m
    memory: 2G
storageClass:
  parameters:
    type: pd-ssd
  provisioner: kubernetes.io/gce-pd
...