---
container:
  args:
    - -config=/root/.factom/private/factomd.conf
    - -customnet=fct_community_test
  image: factominc/factomd
  imageTag: v6.0.1-alpine
  network: testnet
  replicaCount: 1
  resources:
    cpu: 1000m
    memory: 2G

factomd:
  testnet: true
  authority:
    chainID: ''

persistentVolumeClaim:
  size: 20Gi

replicas: 1

service:
  ports:
    api:
      port: 8088
      targetPort: api
      nodePort: 30088
    control-panel:
      port: 8090
      targetPort: control-panel
      nodePort: 30090
    testnet:
      port: 8110
      targetPort: testnet
      nodePort: 30110

storageClass:
  parameters:
    type: pd-ssd
  provisioner: kubernetes.io/gce-pd
...