---
app:
  bitcoinTaxKey: ''
  bitcoinTaxSecret: ''
  currency: USD
  recordCoinbaseReceipts: true
  recordNonCoinbaseReceipts: false
  saveToBitcoinTax: false
  saveToCsv: true
container:
  resources:
    requests:
      memory: "96Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"
factomd:
  host: localhost
  port: 8088
image:
  pullPolicy: Always
  repository: bedrocksolutions/factoid-address-monitord
pod:
  restartPolicy: Always
pvc:
  resources:
    requests:
      storage: 10Gi
statefulSet:
  replicas: 1
volumes:
  config:
    mountPath: /home/node/app/config
  db:
    mountPath: /home/node/app/db
...