---
app:
#  address:
  bitcoinTaxKey: ${BITCOIN_TAX_KEY}
  bitcoinTaxSecret: ${BITCOIN_TAX_SECRET}
  currency: USD
#  nickname:
  recordCoinbaseReceipts: true
  recordNonCoinbaseReceipts: false
  saveToBitcoinTax: false
  saveToCsv: true
container:
  resources:
    requests:
      memory: 96Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 100m
factomd:
  host: localhost
  port: 8088
image:
  name: factoid-address-monitord
  namespace: bedrocksolutions
  pullPolicy: Always
  tag: latest
persistentVolumeClaim:
  initialSize: 10Gi
pod:
  restartPolicy: Always
statefulSet:
  replicas: 1
storageClass:
  parameters:
    type: pd-standard
    replication-type: regional-pd
  provisioner: kubernetes.io/gce-pd
volumes:
  config:
    mountPath: /home/node/app/conf
  csv:
    mountPath: /home/node/app/csv
  db:
    mountPath: /home/node/app/db
...