---
bitcoinTaxKey: ''
bitcoinTaxSecret: ''
currency: USD
host: localhost
imageTag: v1.0
installDir: /home/node/app
port: 8088
recordCoinbaseReceipts: true
recordNonCoinbaseReceipts: false
saveToBitcoinTax: false
saveToCsv: true
...