---
app:
  bitcoinTaxKey: ''
  bitcoinTaxSecret: ''
  currency: USD
  recordCoinbaseReceipts: true
  recordNonCoinbaseReceipts: false
  saveToBitcoinTax: false
  saveToCsv: true
container:
  resources:
factomd:
  host: localhost
  port: 8088
image:
  repository: bedrocksolutions/factoid-address-monitord
  tag: v1.0
pod:
  restartPolicy: Always
pvc:
  resources:
    requests:
      storage: 10Gi
statefulSet:
  replicas: 1
volumes:
  config:
    mountPath: /home/node/app/config
  db:
    mountPath: /home/node/app/db
...