---
app:
#  address:
#  bitcoinTaxKey:
#  bitcoinTaxSecret:
  currency: USD
#  nickname:
  recordCoinbaseReceipts: true
  recordNonCoinbaseReceipts: false
  saveToBitcoinTax: true
  saveToCsv: false
container:
  resources:
    requests:
      memory: "96Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"
factomd:
  host: localhost
  port: 8088
image:
  name: factoid-address-monitord
  namespace: bedrocksolutions
  pullPolicy: Always
  tag: latest
persistentVolumeClaim:
  initialSize: 10Gi
pod:
  restartPolicy: Always
statefulSet:
  replicas: 1
storageClass:
  parameters:
    type: pd-standard
    replication-type: regional-pd
  provisioner: kubernetes.io/gce-pd
volumes:
  config:
    mountPath: /home/node/app/config.json
  db:
    mountPath: /home/node/app/db
...