---
app:
#  address:
#  bitcoinTaxKey:
#  bitcoinTaxSecret:
  currency: USD
#  nickname:
  recordCoinbaseReceipts: true
  recordNonCoinbaseReceipts: false
  saveToBitcoinTax: true
  saveToCsv: false
container:
  resources:
    requests:
      memory: "96Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"
factomd:
  host: localhost
  port: 8088
image:
  name: factoid-address-monitord
  namespace: bedrocksolutions
  pullPolicy: Always
  tag: latest
pod:
  restartPolicy: Always
pvc:
  resources:
    requests:
      storage: 10Gi
statefulSet:
  replicas: 1
volumes:
  config:
    mountPath: /home/node/app/config.json
  db:
    mountPath: /home/node/app/db
...